/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    promotions: Promotion;
    orders: Order;
    customers: Customer;
    'order-emails': OrderEmail;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    customers: {
      orders: 'orders';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'order-emails': OrderEmailsSelect<false> | OrderEmailsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ro' | 'da' | 'en') | ('ro' | 'da' | 'en')[];
  globals: {
    settings: Setting;
    about: About;
    faq: Faq;
    contact: Contact;
  };
  globalsSelect: {
    settings: SettingsSelect<false> | SettingsSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: 'ro' | 'da' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Accounts that can sign in to this admin panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Images used across the shop. Product photos can be uploaded here or directly from a product.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and SEO. Required.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Shop categories used for browsing and filtering products.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Category name shown in the shop (translate per language).
   */
  name: string;
  /**
   * URL segment, e.g. 'conserve' becomes /shop/conserve (translate per language).
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Products shown in the shop. Identity, price and stock live in the sidebar; content in the main panel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Auto-generated "SKU — Title" for admin search and labels
   */
  adminLabel?: string | null;
  /**
   * Unique product code. Also used in the product URL (/produs/<sku>).
   */
  sku: string;
  /**
   * Product name shown to customers (translate per language).
   */
  title: string;
  /**
   * Price in DKK, VAT included (e.g. 49.95).
   */
  priceDkk: number;
  /**
   * Whether the price is per piece or per kilogram.
   */
  unit: 'piece' | 'kg';
  stockStatus: 'in' | 'low' | 'out';
  category?: (number | null) | Category;
  /**
   * The first image is used as the main product photo.
   */
  images?: (number | Media)[] | null;
  /**
   * EU allergen labels listed on the product page.
   */
  allergens?:
    | (
        | 'gluten'
        | 'crustaceans'
        | 'eggs'
        | 'fish'
        | 'peanuts'
        | 'soybeans'
        | 'milk'
        | 'nuts'
        | 'celery'
        | 'mustard'
        | 'sesame'
        | 'sulphites'
        | 'lupin'
        | 'molluscs'
      )[]
    | null;
  /**
   * Ingredient list shown on the product page (translate per language).
   */
  ingredients?: string | null;
  /**
   * Full product description (translate per language).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional ISO country name or code
   */
  countryOfOrigin?: string | null;
  /**
   * Shared keyword for related products on the product page (e.g. bread). Stored lowercase.
   */
  keyword?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Time-boxed discounts applied to selected products. A promotion is live between its start and end dates (inclusive).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  /**
   * Internal label for this promotion (not shown to customers).
   */
  name: string;
  /**
   * Discount percentage applied to the linked products (1–100).
   */
  percentOff: number;
  /**
   * First day the promotion is active (inclusive).
   */
  startDate: string;
  /**
   * Last day the promotion is active (inclusive).
   */
  endDate: string;
  /**
   * The products this promotion discounts.
   */
  products?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders. Confirm new orders, send the payment link, then mark as shipped.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  orderNumber: string;
  /**
   * Shop language the customer ordered in (ro/da/en). Drives email language and the payment-return page.
   */
  locale?: string | null;
  /**
   * Paid or shipped orders can be set to Cancelled after you issue a manual refund in Frisbii (Payment tab → Cancel order, or change status here and save).
   */
  status: 'awaiting_confirmation' | 'awaiting_payment' | 'paid' | 'shipped' | 'cancelled';
  /**
   * Optional link to a saved customer record
   */
  customer?: (number | null) | Customer;
  customerFirstName: string;
  customerLastName: string;
  customerPhone: string;
  customerEmail: string;
  lineItems: {
    /**
     * Reference only — prices are snapshotted below
     */
    product?: (number | null) | Product;
    sku: string;
    productName: string;
    unit: 'piece' | 'kg';
    unitPriceDkk: number;
    quantity: number;
    /**
     * Auto-calculated from unit price × quantity; editable for custom totals
     */
    lineTotalDkk: number;
    /**
     * Customer-ordered quantity before admin adjustment
     */
    originalQuantity?: number | null;
    /**
     * Customer-ordered unit price before admin adjustment
     */
    originalUnitPriceDkk?: number | null;
    lineTotalOverridden?: boolean | null;
    /**
     * Set when quantity, price, line total, or product was changed by admin
     */
    adminAdjusted?: boolean | null;
    id?: string | null;
  }[];
  shippingMethod?: ('pickup' | 'delivery') | null;
  /**
   * Customer delivery address
   */
  customerAddress?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Customer notes for pickup (e.g. preferred time)
   */
  pickupNotes?: string | null;
  /**
   * Optional — add when the order is shipped
   */
  trackingNumber?: string | null;
  paymentProvider?: string | null;
  paymentReference?: string | null;
  paymentLinkUrl?: string | null;
  /**
   * When the payment link was last sent to the customer
   */
  paymentLinkSentAt?: string | null;
  paidAt?: string | null;
  subtotalDkk: number;
  shippingCostDkk?: number | null;
  discountDkk?: number | null;
  totalDkk: number;
  /**
   * True when line items were modified after the order was placed
   */
  hasAdminAdjustments?: boolean | null;
  /**
   * Internal notes (not shown to customer). When cancelling a paid order, include the Frisbii refund reference here.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Guest customer records from checkout, kept for reference and newsletter opt-in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  firstName: string;
  lastName: string;
  phone: string;
  email: string;
  /**
   * Customer opted in to the newsletter at checkout (or later).
   */
  newsletterOptIn?: boolean | null;
  /**
   * When the customer last accepted privacy/data processing at checkout.
   */
  privacyConsentAt?: string | null;
  /**
   * Present for delivery orders; empty for pickup customers.
   */
  address?: {
    street?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Orders linked to this customer from checkout.
   */
  orders?: {
    docs?: (number | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Delivery status of order emails, tracked from Resend webhooks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-emails".
 */
export interface OrderEmail {
  id: number;
  order: number | Order;
  emailType: 'order_received' | 'payment_link' | 'payment_confirmed' | 'order_shipped' | 'order_cancelled';
  /**
   * Resend email id; used to match incoming webhook events.
   */
  resendId?: string | null;
  to?: string | null;
  subject?: string | null;
  status: 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'complained' | 'failed';
  sentAt?: string | null;
  deliveredAt?: string | null;
  openedAt?: string | null;
  clickedAt?: string | null;
  bouncedAt?: string | null;
  lastEventAt?: string | null;
  /**
   * Latest bounce/failure detail reported by Resend, if any.
   */
  lastError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'order-emails';
        value: number | OrderEmail;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  adminLabel?: T;
  sku?: T;
  title?: T;
  priceDkk?: T;
  unit?: T;
  stockStatus?: T;
  category?: T;
  images?: T;
  allergens?: T;
  ingredients?: T;
  description?: T;
  countryOfOrigin?: T;
  keyword?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  percentOff?: T;
  startDate?: T;
  endDate?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  locale?: T;
  status?: T;
  customer?: T;
  customerFirstName?: T;
  customerLastName?: T;
  customerPhone?: T;
  customerEmail?: T;
  lineItems?:
    | T
    | {
        product?: T;
        sku?: T;
        productName?: T;
        unit?: T;
        unitPriceDkk?: T;
        quantity?: T;
        lineTotalDkk?: T;
        originalQuantity?: T;
        originalUnitPriceDkk?: T;
        lineTotalOverridden?: T;
        adminAdjusted?: T;
        id?: T;
      };
  shippingMethod?: T;
  customerAddress?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  pickupNotes?: T;
  trackingNumber?: T;
  paymentProvider?: T;
  paymentReference?: T;
  paymentLinkUrl?: T;
  paymentLinkSentAt?: T;
  paidAt?: T;
  subtotalDkk?: T;
  shippingCostDkk?: T;
  discountDkk?: T;
  totalDkk?: T;
  hasAdminAdjustments?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  email?: T;
  newsletterOptIn?: T;
  privacyConsentAt?: T;
  address?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  orders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-emails_select".
 */
export interface OrderEmailsSelect<T extends boolean = true> {
  order?: T;
  emailType?: T;
  resendId?: T;
  to?: T;
  subject?: T;
  status?: T;
  sentAt?: T;
  deliveredAt?: T;
  openedAt?: T;
  clickedAt?: T;
  bouncedAt?: T;
  lastEventAt?: T;
  lastError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide contact details used in the footer, contact page, and anywhere the shop shows its own email or phone.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Public support email address (shared across all languages).
   */
  email?: string | null;
  /**
   * Public support phone number (shared across all languages).
   */
  phone?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the "Despre" (About us) page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * Page heading (translate per language).
   */
  title?: string | null;
  /**
   * Full page content (translate per language). Use the toolbar for headings, bold, lists, links, etc.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Frequently asked questions shown on the FAQ page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  /**
   * Page heading (translate per language).
   */
  title?: string | null;
  /**
   * Each entry is shown as an expandable question on the FAQ page.
   */
  items?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content for the Contact page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * Page heading (translate per language).
   */
  title?: string | null;
  /**
   * Introduction shown under the heading (translate per language). Use the toolbar for headings, bold, lists, links, etc.
   */
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional free-form content shown below the contact details (translate per language). Format it however you like.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  title?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  title?: T;
  intro?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}